version: "3.6"

services:
  db:
    image: postgres:15-alpine
    container_name: wacky-ride-custom-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - wacky-ride-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

  adminer:
    image: adminer:latest
    container_name: wacky-ride-custom-adminer
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DESIGN=dracula
    depends_on:
      - db

volumes:
  wacky-ride-data: {}
